In [2]:
import matplotlib as mpl
import matplotlib.pyplot as plt
import numpy as np
import sklearn
import pandas as pd
import os
import time
import sys
import tensorflow as tf
from tensorflow.python import keras


print(tf.__version__)
print(sys.version_info)

for module in mpl, np, pd, sklearn, tf, keras:
    print(module.__name__, module.__version__)

2.0.0
sys.version_info(major=3, minor=6, micro=10, releaselevel='final', serial=0)
matplotlib 2.2.2
numpy 1.14.5
pandas 0.23.0
sklearn 0.19.1
tensorflow 2.0.0
tensorflow.python.keras 2.2.4-tf


In [4]:
layer = tf.keras.layers.Dense(100)
layer = tf.keras.layers.Dense(100, input_shape = (None, 5))
layer(tf.zeros([10, 5]))

<tf.Tensor: id=29, shape=(10, 100), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 

In [5]:
layer.variables # layer包含的所有参数
# x * w + b   data * kernel + bias

[<tf.Variable 'dense_2/kernel:0' shape=(5, 100) dtype=float32, numpy=
 array([[-9.88930464e-03, -9.48564857e-02, -1.28009617e-02,
          6.90652877e-02,  1.77567765e-01, -1.82322249e-01,
         -1.45446271e-01,  2.60511786e-02, -2.23695353e-01,
          4.91247326e-02,  1.76299855e-01, -2.23201632e-01,
         -1.02327466e-01, -8.19849223e-02,  2.42454261e-02,
          1.60107538e-01, -1.99323639e-01, -1.12034619e-01,
          4.16848511e-02, -1.31804898e-01,  6.71928674e-02,
         -1.70514390e-01, -4.68868464e-02,  9.06853527e-02,
         -4.25750911e-02,  8.32873136e-02,  1.12355724e-01,
          4.47765142e-02, -2.28252396e-01,  6.42265379e-03,
          2.04930261e-01, -1.91545069e-01, -1.50469229e-01,
         -2.79936790e-02,  8.38227719e-02,  1.72507659e-01,
          2.27833107e-01, -2.38100782e-01, -1.07128665e-01,
         -8.26401114e-02,  8.68048221e-02, -2.26650953e-01,
         -1.83211163e-01,  1.25892952e-01,  3.23087424e-02,
         -8.93074274e-03, -6.4

In [6]:
layer.trainable_variables

[<tf.Variable 'dense_2/kernel:0' shape=(5, 100) dtype=float32, numpy=
 array([[-9.88930464e-03, -9.48564857e-02, -1.28009617e-02,
          6.90652877e-02,  1.77567765e-01, -1.82322249e-01,
         -1.45446271e-01,  2.60511786e-02, -2.23695353e-01,
          4.91247326e-02,  1.76299855e-01, -2.23201632e-01,
         -1.02327466e-01, -8.19849223e-02,  2.42454261e-02,
          1.60107538e-01, -1.99323639e-01, -1.12034619e-01,
          4.16848511e-02, -1.31804898e-01,  6.71928674e-02,
         -1.70514390e-01, -4.68868464e-02,  9.06853527e-02,
         -4.25750911e-02,  8.32873136e-02,  1.12355724e-01,
          4.47765142e-02, -2.28252396e-01,  6.42265379e-03,
          2.04930261e-01, -1.91545069e-01, -1.50469229e-01,
         -2.79936790e-02,  8.38227719e-02,  1.72507659e-01,
          2.27833107e-01, -2.38100782e-01, -1.07128665e-01,
         -8.26401114e-02,  8.68048221e-02, -2.26650953e-01,
         -1.83211163e-01,  1.25892952e-01,  3.23087424e-02,
         -8.93074274e-03, -6.4

In [7]:
help(layer)

Help on Dense in module tensorflow.python.keras.layers.core object:

class Dense(tensorflow.python.keras.engine.base_layer.Layer)
 |  Just your regular densely-connected NN layer.
 |  
 |  `Dense` implements the operation:
 |  `output = activation(dot(input, kernel) + bias)`
 |  where `activation` is the element-wise activation function
 |  passed as the `activation` argument, `kernel` is a weights matrix
 |  created by the layer, and `bias` is a bias vector created by the layer
 |  (only applicable if `use_bias` is `True`).
 |  
 |  Note: If the input to the layer has a rank greater than 2, then
 |  it is flattened prior to the initial dot product with `kernel`.
 |  
 |  Example:
 |  
 |  ```python
 |  # as first layer in a sequential model:
 |  model = Sequential()
 |  model.add(Dense(32, input_shape=(16,)))
 |  # now the model will take as input arrays of shape (*, 16)
 |  # and output arrays of shape (*, 32)
 |  
 |  # after the first layer, you don't need to specify
 |  # the size

In [ ]:
# Customized Dense Layer.
class CustomizedDenseLayer(keras.layers.Layer):
    def __init__(self,units,activation=None,**kwargs):
        self.units = units         #输出的维度
        self.activation = keras.layers.Activation(activation)
        super(CustomizedDenseLayer, self).__init__(**kwargs)
    
    def build(self, input_shape):   # 完成初始化
        """构建所需要的参数"""
        # x * w + b   data * kernel + bias. input_shape:[None, a] w:[a, b] output_shape:[None, b]
        self.kernel = self.add_weight(name='kernel', 
                                      shape=(input_shape[1], self.units),
                                      initializer='uniform',
                                      trainable=True)
        self.bias = self.add_weight(name='bias',
                                    shape(self.units,),
                                    initializer='zero',
                                    trainable=True)
        super(CustomizedDenseLayer, self).build(input_shape)
        
    def call(self, x):     # 完成正向计算
        """完整的正向计算"""
        return self.activation(x @ self.kernel + self.bias)
        
        